services:
  - type: web
    name: slad-back
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: node dist/server.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d

